### ISSUE TITLE
allow customising top level page keys

### ISSUE THREAD

**Issue by misaon** [nuxt/framework#2903]
### Environment

- Operating System: `Linux`
- Node Version:     `v17.4.0`
- Nuxt Version:     `3.0.0-27383920.81ee59c`
- Package Manager:  `yarn@3.1.1`
- Bundler:          `Vite`
- User Config:      `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `normalizedModule()`, `normalizedModule()`

### Reproduction

Create simple page:
`pages/[code].vue`

Visit `http://localhost:3000/test-1`
Go to `http://localhost:3000/test-2` via NuxtLink component

### Describe the bug

After this MR https://github.com/nuxt/framework/pull/2859 and this [change](https://github.com/nuxt/framework/pull/2859/files/917809cef54b8980fe08757b60b455f7cb9e55f9#diff-20895eaf69b2b6f25c4fce199443ac54ad3c6a8fa70985168d50dc86172ef713L6), page not redraw between routes, but url in address bar is changed.

### Additional context

You can explicitly define key on `<NuxtPage :key="route.path" />` but page transitions wont work.
https://github.com/nuxt/framework/pull/2861

![image](https://user-images.githubusercontent.com/15806356/150983302-3323607d-ab67-4a45-bf38-aec6be0da202.png)

**Comment by danielroe** [comment]
(The transition issue should be fixed in https://github.com/nuxt/framework/pull/2904.)

**Comment by misaon** [comment]
> (The transition issue should be fixed in #2904.)

Even with the latest versions they still do not work when `:key` is defined on `<NuxtPage />`

**Comment by misaon** [comment]
if you develop an e-shop, blog or anything where dynamic routes are used, with this bug Nuxt 3 is completely unusable.  For me, this is a bug with P4. Every bigger project use dynamic routes

**Comment by misaon** [comment]
Thanks guys!
