### ISSUE TITLE
Vitest was initialized with native Node instead of Vite Node

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#3252]
The async import doesn't seem to respect the environment of the test runner.

**Reproduction**: https://github.com/danielroe/test-utils-test

cc: @antfu

**Comment by schickling** [comment]
Are you sure this is a problem with Nuxt? I was running into the same problem when running Vitest on pre-compiled `.js` test files with the following config:

```ts
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    include: ['dist/__test__/**/mapping.spec.js'],
    // include: ['src/__test__/**/mapping.spec.ts'],
    exclude: [],
    watchIgnore: [],
  },
})
```

Note: Running the tests on the `src/**/*.spec.ts` files works as expected.

**Comment by antfu** [comment]
Vitest v0.5.1 should fix it.

**Comment by schickling** [comment]
Still doesn't seem to work with `0.5.1`. Here's a repro: https://github.com/schickling-test/2022-feb-vitest-effect/tree/repro/dist-bug

Please run:

- `yarn`
- `yarn dev:ts` (compiles to `./dist`)
- `yarn test`

You should see: 

<img width="627" alt="image" src="https://user-images.githubusercontent.com/1567498/155089489-3501641a-5899-4a15-a006-1965e122cbb9.png">

**Comment by danielroe** [comment]
I can confirm that my issue is no longer reproducible. @schickling, your issue might be a different one that simply has the same symptom - possibly worth raising at the vitest repo?

**Comment by jorge-obsidian** [comment]
> I can confirm that my issue is no longer reproducible. @schickling, your issue might be a different one that simply has the same symptom - possibly worth raising at the vitest repo?

I've just cloned that repo and i'm currently getting the `Error: Vitest was initialized with native Node instead of Vite Node` when launching test.

**Comment by CodyBontecou** [comment]
I'm also running into this. Here's a reproduction [repo](https://github.com/CodyBontecou/nuxt3-vitest-native-node-error).

**Comment by ytr0903** [comment]
In my case, creating `vitest.config.ts` with `test.deps.inline` resolves this error.
```ts:vitest.config.ts
import { defineConfig } from "vitest/config";
export default defineConfig({
  test: {
    environment: "jsdom",
    deps: {
      inline: [/@nuxt\/test-utils-edge/],
    },
  },
})
```

Ref: https://github.com/vitest-dev/vitest/issues/843

**Comment by asmerkin** [comment]
This did not work for me. It's now trying to find jest. 

``` 
Error: [vite]: Rollup failed to resolve import "jest" from "node_modules/@nuxt/test-utils-edge/dist/index.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
 ❯ onRollupWarning node_modules/vite/dist/node/chunks/dep-4da11a5e.js:45916:19
 ❯ onwarn node_modules/vite/dist/node/chunks/dep-4da11a5e.js:45714:13
 ❯ Object.onwarn node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:23225:13
 ❯ ModuleLoader.handleResolveId node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22352:26
 ❯ ModuleLoader.resolveDynamicImport node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22404:120
 ❯ async file:/Users/asmerkin/Workspace/intrepits/elearning-front/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22299:32
```

**Comment by danielroe** [comment]
@asmerkin Would you open a new issue/discussion with a reproduction?

**Comment by asmerkin** [comment]
@danielroe  done here:  https://github.com/nuxt/framework/issues/8594

**Comment by smares** [comment]
I am getting the `Error: Vitest was initialized with native Node instead of Vite Node.` error with `"@nuxt/test-utils-edge": "^3.0.1-rc.0-27828744.aa9aec1"` and `"vitest": "^0.25.3"` with a minimal test following https://nuxt.com/docs/getting-started/testing
