### ISSUE TITLE
`useAsyncData` clears out nested route data before leaving

### ISSUE THREAD

**Issue by mvrlin** [nuxt/framework#4564]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `pnpm@6.32.8`
- Builder:          `vite`
- User Config:      `build`, `buildModules`, `components`, `css`, `srcDir`, `typescript`, `vite`, `server`
- Runtime Modules:  `-`
- Build Modules:    `@intlify/nuxt3@0.1.10`, `@pinia/nuxt@0.1.8`, `nuxt-windicss@2.3.1`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ypbf5b?file=app.vue
To reproduce the issue, load the website with the url `/users/foo` and click **Go Home**

### Describe the bug

`useAsyncData` clears out nested route data before leaving. If the next route is still loading, it produces a blank page, which isn't great 😢 Maybe it is due to provide/inject.

### Additional context

https://user-images.githubusercontent.com/24970784/164979549-cdb21c9c-f791-4a6a-9c7d-a1084f2c78e8.mov

**Comment by Aareksio** [comment]
![image](https://user-images.githubusercontent.com/11166786/165043258-8cb5f224-d6f7-4574-a3cd-2265dbab0bc8.png)
![image](https://user-images.githubusercontent.com/11166786/165043286-dc7d6dee-c6c6-4fdc-ba18-15cdd9b8d770.png)

Works without provide/inject [StackBlitz](https://stackblitz.com/edit/github-ypbf5b-y32kuj).

**Comment by mvrlin** [comment]
> ![image](https://user-images.githubusercontent.com/11166786/165043258-8cb5f224-d6f7-4574-a3cd-2265dbab0bc8.png) ![image](https://user-images.githubusercontent.com/11166786/165043286-dc7d6dee-c6c6-4fdc-ba18-15cdd9b8d770.png)
> 
> Works without provide/inject [StackBlitz](https://stackblitz.com/edit/github-ypbf5b-y32kuj).

Yes, the issue happening, when provide/inject is used. Passing props to deep nested routes is not convenient.

**Comment by danielroe** [comment]
This looks like it might be the same issue as https://github.com/vuejs/core/issues/5513.

**Comment by mvrlin** [comment]
@danielroe https://stackblitz.com/edit/github-kcptvx?file=app.vue same thing is happening, when the route is dynamically nested

**Comment by cinob** [comment]
Experiencing the same problem

**Comment by champ7champ** [comment]
Is the problem being solved? Or should I start inventing crutches?

**Comment by danielroe** [comment]
The route-based data issue is resolved and [is no longer reproducible](https://stackblitz.com/edit/github-kcptvx-c4qpsw), so I'm going to close this. Note that if you are using `provide/inject` to inject data _based on the route_, then this will cause this kind of issue because of how suspense works. You can track https://github.com/vuejs/core/issues/5513 for support for freezing provide/inject through suspense forks...

**Comment by mvrlin** [comment]
@danielroe The problem is still there. Before route changes, it clears the page. It shouldn't be that way.

https://user-images.githubusercontent.com/24970784/190124328-56a10749-c480-450e-b48b-33e7929ca3ad.mov

**Comment by danielroe** [comment]
Did you check the reproduction I linked?

![CleanShot 2022-09-14 at 11 06 35](https://user-images.githubusercontent.com/28706372/190126184-97e9fe28-6b6a-4a96-86b9-18ae93a5f27e.gif)

**Comment by mvrlin** [comment]
@danielroe Please take a look a [this ](https://stackblitz.com/edit/nuxt-starter-vbu67j?file=app.vue)
When leaving nested users/id, it clears out the page.


https://user-images.githubusercontent.com/24970784/190633458-9ccbf568-f26a-42ac-b184-adc7ce73d62a.mov

**Comment by danielroe** [comment]
You should not share a key between the pages. Set it to `user-${route.params.id}` or something.

**Comment by mvrlin** [comment]
> You should not share a key between the pages. Set it to `user-${route.params.id}` or something.

@danielroe I updated the keys, but nothing has changed.. Try out yourself, please.

**Comment by mvrlin** [comment]
@danielroe I think the problem is more deeper than asyncData itself. It's the way that Nuxt handles pages. Instead of loading one by one async page component, it should wait for all nested async pages to be loaded to fully show, like Nuxt2 does it.

**Comment by Luffyyy** [comment]
https://user-images.githubusercontent.com/11510099/191902144-25c10134-1d27-4bcf-bfd2-f0c76aaab330.mp4

Not sure if this is the same issue, but I seem to experience something similar.

Reproduction; https://stackblitz.com/edit/github-f4gpfk-m2cxo3?file=app.vue

**Comment by mvrlin** [comment]
@Luffyyy Yes, as I said previously, it's the way that Nuxt handles async pages. It loads the root route component and then one by one loads the subroute component. Nuxt should wait until all nested pages is loaded before displaying everything.

**Comment by patrikalbertsson** [comment]
I have the same problems. @mvrlin did you find any workaround for this?

**Comment by mvrlin** [comment]
> I have the same problem. @mvrlin did you find any workaround for this?

Unfortunately, no :(

**Comment by carlosmouracorreia** [comment]
Could this be the base for a solution? Based on the suspense feature? I'm pretty sure it's related to how Nuxt handles page changes - https://github.com/vuejs/core/pull/6736

**Comment by Luffyyy** [comment]
For some reason this pull was downgraded from important to minor when it is definitely not a minor bug, it makes nested pages undesirable. It seems to also sit without any updates. I really hope it gets pushed soon otherwise I'm gonna have to get rid of all of the nested routes.

**Comment by mvrlin** [comment]
@Luffyyy I saw Atinux post on the twitter using the `definePageMeta` function. https://twitter.com/atinux/status/1604857928913195009?s=46&t=15UnCrF1REX4Dk39M81dpA

But I have no clue how to use the result from data outside the `definePageMeta`

**Comment by carlosmouracorreia** [comment]
It would be helpful to have some more information about how page transitions are done with Nuxt engine so a temporary solution can be arranged - even if depends on the open PR from Vue3 - this way one could prepare the base ground with a fork and help to ease the mind of people wanting to continue using Nuxt with Vue tooling.
