### ISSUE TITLE
Error: "defuFn is not a function" in 3.0.0-rc.9-xx

### ISSUE THREAD

**Issue by linooohon** [nuxt/framework#7168]
### Environment

------------------------------
- Operating System: `MacOS`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.9-27702110.abd5dc5`
- Package Manager:  `npm@8.15.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

package.json
```json
  "dependencies": {
    "@headlessui/vue": "^1.6.7",
    "@heroicons/vue": "^1.0.6",
    "nuxt": "npm:nuxt3@^3.0.0-rc.9-27702110.abd5dc5",
    "pinia": "^2.0.21",
    "primeicons": "^5.0.0",
    "primevue": "^3.15.0",
    "vue": "^3.2.37"
  }
```

### Describe the bug

When trying to fix loading problem of resources (ex: `js` files..) to follow cdnURL path with the version `3.0.0-rc.9-27702110.abd5dc5`, and the resources loading problem was solved perfectly, thank you!

But there was an error with:

```
__vite_ssr_import_0__.defuFn is not a function
```

> Temp Solution:

I solved it with adding [defu](https://www.npmjs.com/package/defu) dependencies `"defu": "^6.1.0"` in `package.json` for now.

```
npm i defu
```
Has anyone run into the same problem? Or other solutions?
Thank you!

**Comment by 516310460** [comment]
Would you please prodive a reproduction?

**Comment by pxtrez** [comment]
same here but installing `defu` doesn't help

**Comment by lerizen** [comment]
same here with nuxt@3.0.0-rc.9 and @nuxtjsprismic@3.0.0-rc.0

**Comment by manniL** [comment]
> same here with nuxt@3.0.0-rc.9 and @nuxtjsprismic@3.0.0-rc.0

Instead of "same here", please provide a reproduction if the "needs reproduction" label is visible. Feel free to use the starter from https://nuxt.new/

**Comment by lucassimines** [comment]
I'm experiencing the same issue and trying to find the error to create a reproduction. But installing `defu` for now solved the issue.

**Comment by Joaojack** [comment]
Same thing here.
I understand you're asking for a reproduction, but it's a big project and evrything created from scratch would not reflect it.
My project worked with rc8, and I have this error message with rc9 when doing nom run dev.
Could you at least explain the meaning of the error message to do our own research if you don't want to help without reproduction ? 
Thanks
```
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.defuFn is not a function
  at ./.nuxt/app.config.mjs:9:54  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:113:12)  
  at async request (./node_modules/vite-node/dist/client.mjs:136:16)  
  at async ./node_modules/nuxt/dist/app/config.mjs:5:31  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:113:12)  
  at async request (./node_modules/vite-node/dist/client.mjs:136:16)  
  at async ./node_modules/nuxt/dist/app/index.mjs:7:31
```

**Comment by Joaojack** [comment]
Kind of "good" news : after many tries on my project, I just launched a new empty project  with nuxi init and the problem appears the same way !  @danielroe 
So is there something to do with something more hardware or os related ? 

nuxi version : Nuxi 3.0.0-rc.9
node version v16.13.1
npm version 8.19.1
MacBook Air / Apple M1 / 8Go on Monterey 12.4

**Comment by Erica-lyj** [comment]
same here with nuxt@3.0.0-rc.9

**Comment by Erica-lyj** [comment]
after rc.8 upgrade to rc.9  ，npm run dev vuex similar error occurred

**Comment by Erica-lyj** [comment]
> after rc.8 upgrade to rc.9 ，npm run dev vuex similar error occurred
```
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.createStore is not a function
  at C:/project/nuxt-test/website-mobile/store/index.ts:5:37
  at async ViteNodeRunner.directRequest (/C:/project/nuxt-test/website-mobile/node_modules/vite-node/dist/client.mjs:217:5)
  at async ViteNodeRunner.cachedRequest (/C:/project/nuxt-test/website-mobile/node_modules/vite-node/dist/client.mjs:113:12)
  at async request (/C:/project/nuxt-test/website-mobile/node_modules/vite-node/dist/client.mjs:136:16)
  at async C:/project/nuxt-test/website-mobile/pages/buyin.vue?macro=true:11:31
  at async ViteNodeRunner.directRequest (/C:/project/nuxt-test/website-mobile/node_modules/vite-node/dist/client.mjs:217:5)
  at async ViteNodeRunner.cachedRequest (/C:/project/nuxt-test/website-mobile/node_modules/vite-node/dist/client.mjs:113:12)
  at async request (/C:/project/nuxt-test/website-mobile/node_modules/vite-node/dist/client.mjs:136:16)
  at async virtual:nuxt:C:/project/nuxt-test/website-mobile/.nuxt/routes.mjs:1:238
  at async ViteNodeRunner.directRequest (/C:/project/nuxt-test/website-mobile/node_modules/vite-node/dist/client.mjs:217:5)
```

**Comment by Joaojack** [comment]
Not theexact  same error msg @Erica-lyj , different issue I'm afraid ?

**Comment by Joaojack** [comment]
Update : I confirm the problem _only occurs on Mac_. Same repo, same update made on my windows 10 computer, no error.

**Comment by ArmadOon** [comment]
im creating brand new project with npx nuxi init <Project-name> and when i run npm run dev same problem happen. Im on mac

**Comment by Raduc4** [comment]
Same issue, 
Fedora
Node v16.14.0

`npm init vite my-project` -> Nuxt project

Barebone project fails

```
Nuxi 3.0.0-rc.9                                                                                                                                    20:42:04
Nuxt 3.0.0-rc.9 with Nitro 0.5.1                                                                                                                   20:42:04
                                                                                                                                                   20:42:06
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.100.44:3000/
  > Network:  http://172.24.0.1:3000/

ℹ Vite client warmed up in 766ms                                                                                                                   20:42:08
ℹ Vite server warmed up in 270ms                                                                                                                   20:42:08
✔ Nitro built in 730 ms                                                                                                                      nitro 20:42:09
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.defuFn is not a function
  at ./.nuxt/app.config.mjs:9:54  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:113:12)  
  at async request (./node_modules/vite-node/dist/client.mjs:136:16)  
  at async ./node_modules/nuxt/dist/app/config.mjs:5:31  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:113:12)  
  at async request (./node_modules/vite-node/dist/client.mjs:136:16)  
  at async ./node_modules/nuxt/dist/app/index.mjs:7:31  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)
```

**Comment by pxtrez** [comment]
> Update : I confirm the problem _only occurs on Mac_. Same repo, same update made on my windows 10 computer, no error.

The problem also exists on windows 11

**Comment by Joaojack** [comment]
Stuck for two days here. Rolled back to rc8, wished i rolled back to Nuxt 2 for my project...

**Comment by iDSeGe** [comment]
I have also had the same error since today. I have just recreated the project and have not made any changes to the standard.

`$ nuxt dev -o

Nuxi 3.0.0-rc.9                                                                      16:38:57
Nuxt 3.0.0-rc.9 with Nitro 0.5.1                                                     16:38:57
                                                                                     16:38:58
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.0.170:3000/

ℹ Vite client warmed up in 301ms                                                     16:38:59
ℹ Vite server warmed up in 72ms                                                      16:38:59
✔ Nitro built in 205 ms                                                        nitro 16:38:59
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.defuFn is not a function
  at ./.nuxt/app.config.mjs:9:54  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:113:12)  
  at async request (./node_modules/vite-node/dist/client.mjs:136:16)  
  at async ./node_modules/nuxt/dist/app/config.mjs:5:31  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:113:12)  
  at async request (./node_modules/vite-node/dist/client.mjs:136:16)  
  at async ./node_modules/nuxt/dist/app/index.mjs:7:31  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.defuFn is not a function
  at ./.nuxt/app.config.mjs:9:54  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:113:12)  
  at async request (./node_modules/vite-node/dist/client.mjs:136:16)  
  at async ./node_modules/nuxt/dist/app/config.mjs:5:31  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:113:12)  
  at async request (./node_modules/vite-node/dist/client.mjs:136:16)  
  at async ./node_modules/nuxt/dist/app/index.mjs:7:31  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)`

**Comment by MerlinPerrotLegler** [comment]
Same issue, only removed the the node_modules folder and changed to "nuxt": "3.0.0-rc.8" in the package.json

**Comment by gpicron** [comment]
Same issue.

On Mac (Intel), 

Happened just after I made a npm -g upgrade, then created a brand new with npx nuxi init -t doc-driven ui.
I'm using brew too, it caused issues in the past with npm global package (maybe a track).

**Comment by Joaojack** [comment]
Wow @gpicron what you wrote is a huge deal : I've uninstalled homebrew on my Mac, and now rc9 works and the defuFn error message is gone ! That's not a complete solution and doesn't explain what the problem was, but I take it.

**Comment by mobayen** [comment]
I have same issue on a fresh Nuxt RC9
just :

1. `npx nuxi init nuxt-app`
2. `npm install`
3. `npm run dev`

Same happens when I tried yarn

**Comment by JagrutiPancham** [comment]
just write ssr: false in nuxt.config.ts

**Comment by Joaojack** [comment]
> just write ssr: false in nuxt.config.ts

...Except if you want server side rendering 🙃

**Comment by joseph-montanez** [comment]
> 

Doesnt fix it, just pushed the problem to the client: Here is what you get in the console of a web browser instead.

app.config.mjs:2 Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.vite/deps/defu.js?v=5440456e' does not provide an export named 'defuFn' (at app.config.mjs:2:10)

**Comment by joseph-montanez** [comment]
> just write ssr: false in nuxt.config.ts

Doesnt fix it, just pushed the problem to the client: Here is what you get in the console of a web browser instead.

app.config.mjs:2 Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.vite/deps/defu.js?v=5440456e' does not provide an export named 'defuFn' (at app.config.mjs:2:10)

**Comment by joseph-montanez** [comment]
I was able to track down the issue to not Nuxt specially but using including @nuxtjs/axios breaks it. Here is my repo to reproduce the issue:

https://github.com/joseph-montanez/nuxt-framework-issue-7168

```bash
npm i
npm run dev
```

**Comment by arafays** [comment]
It's kind of frustrating seeing it tagged **need reproduction** when the only commands I have run are

Operating system: `Windows 10 x64`
Node version: `16.14.2`

```
npx nuxi init app
yarn install
yarn dev
```
and then you spend hours figuring out where you went wrong and find the issue that is 10 days old 

```

i Vite server warmed up in 1127ms
i Vite client warmed up in 3697ms
√ Nitro built in 1747 ms
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.defuFn is not 
a function
  at./.nuxt/app.config.mjs:9:54
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:113:12)
  at async request (./node_modules/vite-node/dist/client.mjs:136:16)
  at async./node_modules/nuxt/dist/app/config.mjs:5:31
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:113:12)
  at async request (./node_modules/vite-node/dist/client.mjs:136:16)
  at async./node_modules/nuxt/dist/app/index.mjs:7:31
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.defuFn is not 
a function
  at./.nuxt/app.config.mjs:9:54
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:113:12)
  at async request (./node_modules/vite-node/dist/client.mjs:136:16)
  at async./node_modules/nuxt/dist/app/config.mjs:5:31
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:113:12)
  at async request (./node_modules/vite-node/dist/client.mjs:136:16)
  at async./node_modules/nuxt/dist/app/index.mjs:7:31
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:217:5)
```

**Comment by manniL** [comment]
> It's kind of frustrating seeing it tagged need reproduction when the only commands I have run are

You already showcased the problem quite well. The commands *you* have to run. 
Just because the issue pops up for you (and a hand full of people), it doesn't mean it is easy to reproduce 🙈
Actually it is quite the opposite.

I tried doing exactly what you wrote and do not receive any errors. 😅

**Comment by Joaojack** [comment]
I solved the problem in my case just by doing one thing (even if that sounds weird) : 
- Uninstall homebrew on my mac
- Upgrading nuxt
- Reinstalling homebrew (because i need it)

**Comment by joseph-montanez** [comment]
> Just because the issue pops up for you (and a hand full of people), it doesn't mean it is easy to reproduce 🙈
> Actually it is quite the opposite.

I've provided a Github Repo that produces the issue 100% of the time:

https://github.com/joseph-montanez/nuxt-framework-issue-7168

npm i
npm run dev

Installing Nuxt on its own works fine, its when its combined with a library. I've tried this on my Linux, two Windows 10 and two Mac Mini's (Intel and M1). They all exhibit the same issue. I did add a docker instance but its not working at the moment.

**Comment by manniL** [comment]
> > Just because the issue pops up for you (and a hand full of people), it doesn't mean it is easy to reproduce 🙈
> > Actually it is quite the opposite.
> 
> I've provided a Github Repo that produces the issue 100% of the time:
> 
> [joseph-montanez/nuxt-framework-issue-7168](https://github.com/joseph-montanez/nuxt-framework-issue-7168)
> 
> npm i npm run dev
> 
> Installing Nuxt on its own works fine, its when its combined with a library. I've tried this on my Linux, two Windows 10 and two Mac Mini's (Intel and M1). They all exhibit the same issue. I did add a docker instance but its not working at the moment.

It can be reproduced that way 👏🏻

**Comment by todpale** [comment]
> @joseph-montanez But why is `@nuxtjs/axios` included? It is a Nuxt2 module 🤔
> 
> 
> 
> When removing it from `package.json` and recreate lockfile, things work accordingly 👍🏻

I had the same issue. Nuxt 3 RC 10, I just removed @nuxtjs/axios and installed Defu. Now it works like a charm.

**Comment by Unearthlyglow** [comment]
I've been following this thread for 3-4 days now and each day I've had the same issue. TODAY(9/15/22) I try it and everything worked.

**Comment by pxtrez** [comment]
the problem still exists for me, even after updating to rc10 and installing defu

**Comment by manniL** [comment]
@pxtrez Did you check you don't have a Nuxt2-only module installed?

**Comment by pxtrez** [comment]
the modules in my nuxt.config are  `@nuxtjs/tailwindcss`, `@nuxt/image-edge` and `@nuxt/content` so ig they shouldn't cause this problem

**Comment by joseph-montanez** [comment]
> the modules in my nuxt.config are `@nuxtjs/tailwindcss`, `@nuxt/image-edge` and `@nuxt/content` so ig they shouldn't cause this problem

Maybe double check you have the latest versions and nuke package-lock.json/node_modules. I am leaning on Defu 6.0.0 -> 6.1.0 is causing resolution problems. If its still a problem try `npm cache clean –force` along with removing node_modules & package-lock.json

**Comment by shiv122** [comment]
i am still getting this issue.  any solution??

**Comment by QaahirStewart** [comment]
same here no clear answer, im going to try wait until rc.11 to see if they fix it

**Comment by shiv122** [comment]
check if you have any node_module in your home directory.
for ex. if you are on windows goto c/Users/<you username>  and check for node_module folder.
if theres on rename or delete it.
this works for me.
[source](https://pullanswer.com/questions/rc-9-rc-10-cannot-read-properties-of-undefined-reading-modules-when-vue-is-installed-in-parent-dir)

**Comment by QaahirStewart** [comment]
This worked many thankss

**Comment by chiuwah** [comment]
Just tried edge channel https://v3.nuxtjs.org/getting-started/upgrade-guide/edge-channel/ and no problems in Nuxt 3.0.0-rc.11-27727864.720da64 with Nitro 0.5.4-27726613.640c2b7

**Comment by pxtrez** [comment]
Gotcha! I set the nuxt version to "npm:nuxt3@latest" and it seems to be working! Thanks for your help!

**Comment by anovsiradj** [comment]
this also happened to [hn](https://github.com/nuxt/hackernews), when `npm run dev`

```
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.defuFn is not a function
  at D:/NodeProjects/hn-nuxtjs/.nuxt/app.config.mjs:9:54
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async ViteNodeRunner.directRequest (/D:/NodeProjects/hn-nuxtjs/node_modules/vite-node/dist/client.mjs:251:5)
  at async ViteNodeRunner.cachedRequest (/D:/NodeProjects/hn-nuxtjs/node_modules/vite-node/dist/client.mjs:128:12)
  at async request (/D:/NodeProjects/hn-nuxtjs/node_modules/vite-node/dist/client.mjs:151:16)
  at async D:/NodeProjects/hn-nuxtjs/node_modules/nuxt/dist/app/config.mjs:5:31
  at async ViteNodeRunner.directRequest (/D:/NodeProjects/hn-nuxtjs/node_modules/vite-node/dist/client.mjs:251:5)
  at async ViteNodeRunner.cachedRequest (/D:/NodeProjects/hn-nuxtjs/node_modules/vite-node/dist/client.mjs:128:12)
  at async request (/D:/NodeProjects/hn-nuxtjs/node_modules/vite-node/dist/client.mjs:151:16)
  at async D:/NodeProjects/hn-nuxtjs/node_modules/nuxt/dist/app/index.mjs:7:31
```

windows: 10, node: v16.17.0, npm: v8.19.2;

**Comment by QaahirStewart** [comment]
@anovsiradj i got it fixed by for deleting node modules in my directories.
ex. if you are on windows goto c/Users/ and check for node_module folder.

**Comment by danielroe** [comment]
Closing as this is a package manager issue. @pi0 feel free to reopen if you have any ideas about anything we can do to prevent this...

**Comment by kingrea** [comment]
I have the same issue when updating from rc.8 to rc.9, then updated to rc.12 and it's still happening.

`async ViteNodeRunner.directRequest (/Q:/Site-Education/node_modules/vite-node/dist/client.mjs:250:5)`
seems to be causing it.

**Comment by iq5sa** [comment]
Just change your nuxtjs version to 3.0.0-rc.8 in  package.json to downgrade.
And don't forget to run `npm install`
