### ISSUE TITLE
Error after upgrading to 3.0.0-rc.9: the requested module 'untyped' does not provide an export named 'defineUntypedSchema' 

### ISSUE THREAD

**Issue by rizypb** [nuxt/framework#7227]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.20.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

This issue was happened after upgrading to `"nuxt": "3.0.0-rc.9"` from `"nuxt": "3.0.0-rc.6"`

### Describe the bug

Error after upgrading to 3.0.0-rc.9: the requested module 'untyped' does not provide an export named 'defineUntypedSchema' 
 SyntaxError: The requested module 'untyped' does not provide an export named 'defineUntypedSchema'

### Logs

```shell
ERROR  Cannot start nuxt:  The requested module 'untyped' does not provide an export named 'defineUntypedSchema' 

  import { defineUntypedSchema } from 'untyped';
  ^^^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module 'untyped' does not provide an export named 'defineUntypedSchema'
  at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
  at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
  at async Loader.import (internal/modules/esm/loader.js:178:24)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:686:37)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6767:23)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6826:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by 516310460** [comment]
Would you please prodive a reproduction?

**Comment by danielroe** [comment]
Looks like you have an outdated version of untyped installed. Try running `yarn upgrade untyped`

**Comment by rizypb** [comment]
> Would you please prodive a reproduction?

Provided. Thank you

**Comment by VladimirCores** [comment]
Still present in `"nuxt": "3.0.0-rc.10"`

```
yarn dev
yarn run v1.22.19
$ nuxt dev
Nuxi 3.0.0-rc.10                                                                                                                                    21:07:34
Nuxt 3.0.0-rc.10 with Nitro 0.5.3                                                                                                                   21:07:35

 ERROR  The requested module 'untyped' does not provide an export named 'defineUntypedSchema'                                                       21:07:35

  import { defineUntypedSchema } from 'untyped';
  ^^^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module 'untyped' does not provide an export named 'defineUntypedSchema'
  at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
  at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
  at async Loader.import (internal/modules/esm/loader.js:178:24)
  at async loadKit (node_modules/nuxi/dist/shared/nuxi.71bafe5d.mjs:5:12)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6751:37)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Only:
```
"devDependencies": {
    "@iconify/json": "^2.1.102",
    "@iconify/vue": "^3.2.1",
    "@nuxtjs/eslint-config-typescript": "^11.0.0",
    "@nuxtjs/google-fonts": "^3.0.0-0",
    "animejs": "^3.2.1",
    "eslint": "^8.23.1",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "nuxt": "3.0.0-rc.10",
    "nuxt-windicss": "^2.4.3",
    "prettier": "^2.7.1"
  }
```

**Comment by danielroe** [comment]
Just to be clear, this is an issue with a package manager installing an outdated package, likely because of another dependency. Nuxt itself is not causing this issue.

**Comment by yeonjulee1005** [comment]
also in my project, same problem

`Nuxt 3.0.0-rc.10 with Nitro 0.5.3                                                                                                                                                                                                     09:48:33

 ERROR  The requested module 'untyped' does not provide an export named 'defineUntypedSchema'                                                                                                                                         09:48:33

  import { defineUntypedSchema } from 'untyped';
  ^^^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module 'untyped' does not provide an export named 'defineUntypedSchema'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
  at async loadKit (node_modules/nuxi/dist/shared/nuxi.71bafe5d.mjs:5:12)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6751:37)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by ktiedt** [comment]
Seems to be related to the `@pinia/nuxt` module + RC 3... started hitting this problem when I tried implementing a pinia store and added the module to the nuxt config.

**Comment by Utitofon-Udoekong** [comment]
Same here. I added the @pinia/nuxt module and encountered the problem.

**Comment by RijaCloud** [comment]
@danielroe I am not using yarn,  so this doesn't really help me.

**Comment by Brwmaster** [comment]
> @danielroe I am not using yarn, so this doesn't really help me.

Just run `npm update` it should fix the issue (at least it did for me)

**Comment by VladimirCores** [comment]
All my problems gone in rc.11. Thanks.

**Comment by rizypb** [comment]
@danielroe 
This issue is still happening and when I run `npm update` its throwing me this:
```
Nuxi 3.0.0-rc.11                                                                                                            
Nuxt 3.0.0-rc.11 with Nitro 0.5.4                                                                                 

 ERROR  Cannot find package '/node_modules/@nuxt/kit/node_modules/c12/' imported from /node_modules/@nuxt/kit/dist/index.mjs
Did you mean to import c12/dist/index.cjs?
```

**Comment by TeodorDre** [comment]
Updating @pinia/nuxt to 0.4.2 solves the problem
