### ISSUE TITLE
cannot import from `nuxt/app` (Package import specifier "#build/app.config.mjs" is not defined)

### ISSUE THREAD

**Issue by iamdagy** [nuxt/framework#7244]
### Environment

Operating System: MacOS Ventura
Node Version: v16.13.0.
Nuxt Version: 3.0.0-rc.9
Nitro Version: 0.5.0
Package Manager: yarn@1.22.19
Builder: webpack ( I think)
User Config:
Runtime Modules:
  "dependencies": {
    "@formkit/i18n": "^1.0.0-beta.10",
    "@pinia/nuxt": "^0.4.1",
    "axios": "^0.27.2",
    "pinia": "^2.0.21",
    "pinia-plugin-persistedstate": "^2.1.1",
    "postmark": "^3.0.1",
    "swiper": "^8.3.1",
    "vue3-marquee": "^3.0.7"
  }
Build Modules:
"devDependencies": {
    "@aceforth/nuxt-netlify": "^1.1.0",
    "@formkit/nuxt": "^1.0.0-beta.11-0dd967c",
    "@iconify-json/heroicons-solid": "^1.1.1",
    "@nuxtjs/tailwindcss": "^5.3.2",
    "@tailwindcss/typography": "^0.5.7",
    "@vueuse/core": "^9.1.1",
    "@vueuse/nuxt": "^9.1.1",
    "netlify-cli": "^11.5.1",
    "nuxt": "3.0.0-rc.9",
    "unplugin-icons": "^0.14.5"
  }

### Reproduction

I upgrade with yarn upgrade and with yarn upgrade nuxt, then yarn upgrade --force, and then yarn upgrade --latest.
I upgraded to RC.9 and a few packages that didn't work I upgraded manually to the edge repository like formkit that needed yarn add @formkit/nuxt@next --dev .

I'will try to make a minimal reproduction, but as the project has many pages and components Im not sure if I have to recreate the whole project.

### Describe the bug

When I do yarn build -> the site is completely broken it doesn't load any page.
When I do yarn dev -> the site works ok
When I do yarn check -> There is 1 error
```
error "@pinia/nuxt#unctx#unplugin#vite@^2.3.0" doesn't satisfy found match of "vite@3.0.9"
error Found 1 errors.
```

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Package import specifier "#build/app.config.mjs" is not defined in package /Users/david/WebstormProjects/mixverde/.output/server/node_modules/nuxt/package.json imported from /Users/david/WebstormProjects/mixverde/.output/server/node_modules/nuxt/dist/app/config.mjs
  at new NodeError (node:internal/errors:371:5)  
  at throwImportNotDefined (node:internal/modules/esm/resolve:429:9)  
  at packageImportsResolve (node:internal/modules/esm/resolve:778:3)  
  at moduleResolve (node:internal/modules/esm/resolve:924:21)  
  at defaultResolve (node:internal/modules/esm/resolve:1044:11)  
  at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)  
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)  
  at link (node:internal/modules/esm/module_job:75:36)```
```

**Comment by emaia** [comment]
Same to me. yarn dev works but yarn generate throw an error. My package contains:

```json
"devDependencies": {
    "@nuxt/image": "^0.7.1",
    "@nuxtjs/tailwindcss": "^5.3.2",
    "nuxt": "3.0.0-rc.9",
    "vue-gtag-next": "^1.14.0"
  },
  "dependencies": {
    "@splidejs/vue-splide": "^0.6.7"
  }
```

Error log:

```
Nuxt 3.0.0-rc.9 with Nitro 0.5.1                                                                                                                                                             08:58:48
ℹ Using Tailwind CSS from ~/assets/css/tailwind.css                                                                                                                         nuxt:tailwindcss 08:58:57
ℹ Client built in 2815ms                                                                                                                                                                     08:59:01
ℹ Building server...                                                                                                                                                                         08:59:01
✔ Server built in 806ms                                                                                                                                                                      08:59:02
✔ Generated public .output/public                                                                                                                                                      nitro 08:59:02
ℹ Initializing prerenderer                                                                                                                                                             nitro 08:59:02
ℹ Prerendering 1 initial routes with crawler                                                                                                                                           nitro 08:59:04

 ERROR  [nuxt] [request error] [unhandled] [500] Package import specifier "#build/app.config.mjs" is not defined in package /home/.../node_modules/nuxt/package.jso
n imported from /home/.../node_modules/nuxt/dist/app/config.mjs
  at new NodeError (node:internal/errors:372:5)
  at throwImportNotDefined (node:internal/modules/esm/resolve:461:9)
  at packageImportsResolve (node:internal/modules/esm/resolve:841:3)
  at moduleResolve (node:internal/modules/esm/resolve:997:21)
  at defaultResolve (node:internal/modules/esm/resolve:1218:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
  at link (node:internal/modules/esm/module_job:78:36)


 ERROR  [nuxt] [request error] [unhandled] [500] Package import specifier "#build/app.config.mjs" is not defined in package /home/.../node_modules/nuxt/package.jso
n imported from /home/.../node_modules/nuxt/dist/app/config.mjs
  at new NodeError (node:internal/errors:372:5)
  at throwImportNotDefined (node:internal/modules/esm/resolve:461:9)
  at packageImportsResolve (node:internal/modules/esm/resolve:841:3)
  at moduleResolve (node:internal/modules/esm/resolve:997:21)
  at defaultResolve (node:internal/modules/esm/resolve:1218:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
  at link (node:internal/modules/esm/module_job:78:36)


 ERROR  [nuxt] [request error] [unhandled] [500] Package import specifier "#build/app.config.mjs" is not defined in package /home/.../node_modules/nuxt/package.jso
n imported from /home/.../node_modules/nuxt/dist/app/config.mjs
  at new NodeError (node:internal/errors:372:5)
  at throwImportNotDefined (node:internal/modules/esm/resolve:461:9)
  at packageImportsResolve (node:internal/modules/esm/resolve:841:3)
  at moduleResolve (node:internal/modules/esm/resolve:997:21)
  at defaultResolve (node:internal/modules/esm/resolve:1218:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
  at link (node:internal/modules/esm/module_job:78:36)

  ├─ / (82ms) (Error: [500] Internal Server Error)                                                                                                                                     nitro 08:59:04  
✔ You can now deploy .output/public to any static hosting!
```

**Comment by bndrgroup** [comment]
+1 - removing vue dependency from package.json and then running the dev server works fine, however when building for production we get:

`request error] [unhandled] [500] The requested module 'vue' does not provide an export named 'default'`

**Comment by huang-julien** [comment]
does it work if you set experimental.externalVue to false in nuxt.config ?

**Comment by iamdagy** [comment]
> does it work if you set experimental.externalVue to false in nuxt.config ?

@huang-julien just tried your suggestion but the same problem continuos. Thanks for the suggestion.

**Comment by mshadowz** [comment]
same here. im using npm and upgrading from rc8

**Comment by danielroe** [comment]
Please ensure you are not importing directly from `nuxt/app` but from `#imports`.

**Comment by boboldehampsink** [comment]
Seeing the same on my end with rc9

**Comment by fatcarter** [comment]
+1 Is there a temporary solution in place?

**Comment by emaia** [comment]
> Please ensure you are not importing directly from `nuxt/app` but from `#imports`.

@danielroe This worked for me. thanks!

**Comment by Lyokolux** [comment]
I bumped my dependency and I am facing this issue with `histoire`.

I get:
```
TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier "#build/app.config.mjs" is not defined in package node_modules/nuxt/package.json imported from node_modules/nuxt/dist/app/config.mjs
```

**Comment by ady642** [comment]
same error as @Lyokolux but with `vitest`

**Comment by boboldehampsink** [comment]
> same for me as @Lyokolux but with `vitest`

I fixed it by inlining nuxt as a dep

**Comment by iamdagy** [comment]
> Please ensure you are not importing directly from `nuxt/app` but from `#imports`.

@danielroe what do you mean ? should I change 
import { defineNuxtConfig } from 'nuxt' 
to import { defineNuxtConfig } from '#imports' 

 or where do I make the change? how did you fixed it @emaia

**Comment by danielroe** [comment]
No, your Nuxt config is the one place you should import anything from `nuxt` in your app.

**Comment by iamdagy** [comment]
> No, your Nuxt config is the one place you should import anything from `nuxt` in your project.

I see, thanks for clarifying that. I changed it in one place but the problem persist.
as far as I can see I was importing from one plugin so I changed it 
from
import {defineNuxtPlugin, useCookie} from '#app'
to
import {defineNuxtPlugin, useCookie} from '#imports'

**Comment by emaia** [comment]
@iamdagy I updated my code in plugins folder.

```js
import {defineNuxtPlugin} from "#imports";
```

@danielroe My nuxt.config.ts was not changed and has `import {defineNuxtConfig} from 'nuxt'` not "#imports"

**Comment by iamdagy** [comment]
> 

@boboldehampsink  how did you add Nuxt as a dependency?
@emaia  did you do this also? I have just one plugin for Pinia and did make the change to #imports but Im still seeing the same error.

Thanks

**Comment by boboldehampsink** [comment]
I'm talking about vitest config - see https://vitest.dev/config/#deps-inline

**Comment by iamdagy** [comment]
> I'm talking about vitest config - see https://vitest.dev/config/#deps-inline

@boboldehampsink I see, Im not using vitest. thanks for the info.

**Comment by iamdagy** [comment]
> No, your Nuxt config is the one place you should import anything from `nuxt` in your project.

@danielroe can I still import from cue from pages and components? I mean thinks like ref, watch and so on?
import {nextTick, onMounted, ref, watch, watchEffect} from "vue";

I can't find any other import from Nuxt, Nuxt/app, or #app

**Comment by Lyokolux** [comment]
> I'm talking about vitest config - see https://vitest.dev/config/#deps-inline

Does anyone knows how to inline deps with vite such as vitest does to fix it ? I don't find it in their docs.

**Comment by iamdagy** [comment]
I was indeed importing from Nuxt/app in another place ( the Pinia Store) after changing it to #imports everything works now.

Thanks

**Comment by simllll** [comment]
I'm confused, so Instead of importing from nuxt/app we have to import from "#imports".. well, it sounds strange, but okay...  But if I do so, i get:
` ERROR  Failed to resolve import "#import" from "src/pages/index.vue". Does the file exist? (repeated 2 times)                                                                                                        09:18:56
`
Are there some special places where we have to use #imports and some where de are not alloewd to do so? Or do I miss somethign else?

**Comment by simllll** [comment]
And my IDE says now 
![image](https://user-images.githubusercontent.com/5757263/189595476-dc23983e-067e-4467-84d9-bd259809c483.png)

and there is furthermore also no type inference possilbe now?

**Comment by danielroe** [comment]
@simllll Would you raise a new issue if you can reproduce this? This is what I see...

![CleanShot 2022-09-12 at 09.18.13.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2022_09_12_at_09_18_13_2834993404.png)

**Comment by Lyokolux** [comment]
> And my IDE says now ![image](https://user-images.githubusercontent.com/5757263/189595476-dc23983e-067e-4467-84d9-bd259809c483.png)
> 
> and there is furthermore also no type inference possilbe now?

You could run `nuxi prepare` to generate the `.d.ts` files again, or restart your TS server. Does the error still appear?

**Comment by simllll** [comment]
Ah yes sorry, i figured it out already here: https://github.com/nuxt/framework/issues/7434

**Comment by poteboy** [comment]
> You could run nuxi prepare to generate the .d.ts files again, or restart your TS server. Does the error still appear?

I'm still facing the same issue. replacing '#imports' w '#import' does not work either

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.

**Comment by husayt** [comment]
Still see this with Histoire

**Comment by danielroe** [comment]
Then please do raise an issue there with a reproduction. Feel free to tag me.

**Comment by floriankapaun** [comment]
This still occurs to me while running tests via `yarn vitest` using `nuxt@3.0.0-rc.11`.

Inlining deps as @boboldehampsink mentioned didn't do the trick for me.

My Error still remains:
```
TypeError: Package import specifier "#build/app.config.mjs" is not defined in package /Users/.../app/node_modules/nuxt/package.json imported from /Users/.../app/node_modules/nuxt/dist/app/config.mjs
```

After tracking it further down, it seems like the error occurs only if `import { useRuntimeConfig } from '#imports'` is used. But according to previous comments, this should work, no @danielroe?

**Comment by danielroe** [comment]
Yes, this should work, assuming you are using nuxt/test-utils and not unit testing that component. (Follow https://github.com/nuxt/framework/issues/2465 for unit testing support.)

**Comment by ChurikiTenna** [comment]
I am experiencing the same issue.
Using rc12.

replacing nuxt/app with #imports removed the error, instead, caused this new error:
Cannot find module '#imports' or its corresponding type declarations.
Editing tsconfig according to https://github.com/nuxt/framework/issues/7434 didn't resolve my case.

**Comment by danielroe** [comment]
@ChurikiTenna Would you open a new issue with a reproduction?
