### ISSUE TITLE
generated 200.html references /200.html/_payload.js

### ISSUE THREAD

**Issue by some-user123** [nuxt/framework#7548]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

- Run `nuxt generate` on nuxt3 project.

### Describe the bug

It's great to have the fallback file `200.html` now! 💖

However, the fallback file `200.html` references a `/200.html/_payload.js` which does not exist.

```html
<!DOCTYPE html>
<html >
<head><link rel="modulepreload" href="/200.html/_payload.js"><link rel="modulepreload" as="script" crossorigin...
```

This causes this error in the console as the `200.html` is served as a fallback 😁
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

Not sure if this is the reason, the fallback is not working properly, but let's take one step at a time 😉

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/) via https://github.com/nuxt/framework/pull/7535.

**Comment by some-user123** [comment]
On the edge channel, a file name "undefined" is referenced:

```html
<!DOCTYPE html>
<html >
<head><link rel="modulepreload" href="undefined"><link ...
```

It's still the same error in the console as also "undefined" falls back to "200.html" 😉
