### ISSUE TITLE
rc.12 build and preview server always show ERR_CONNECTION_RESET when visited using chrome browser

### ISSUE THREAD

**Issue by annndddy** [nuxt/framework#8450]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

create a new nuxt rc12 project
npx nuxi init nuxt-rc12

build and preview
yarn run build
yarn run preview

### Describe the bug

visit localhost:3000 using chrome browser
it cannot reach the page and show
ERR_CONNECTION_RESET
and no error & any message on the server terminal

i had try to deploy the build server to azure app service which is using windows and it not work too

i tried yarn run dev and the page work fine, it only not work on the build command

everything works when using rc.11

**Comment by agracia-foticos** [comment]
Same issue

**Comment by luke-z** [comment]
I'm experiencing the same problem with WSL2 on Windows 10, works with `yarn dev`, but doesn't work with `yarn build && node .output/server/index.mjs`. 
At first I thought it's a Nuxt config problem, but my colleague was able to open the prod site on his macbook.

I can curl the page from Windows and WSL2.

Browsers won't open it though.

**Comment by paramono** [comment]
I can confirm that's not a Windows-specific issue: server built on rc.12 cannot be accessed.
Downgrading to rc.11 helps.

**Comment by adamiss5138** [comment]
I tried to run the production build of version 3.0.0-rc12 behind Apache2 reverse proxy and I was constantly getting ERR_HTTP2_PROTOCOL_ERROR.
Downgraded to rc11 and seems to be working just fine.

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.

**Comment by paramono** [comment]
I am experiencing the same issue with rc14
Does anybody still experience the same issue?

**Comment by luke-z** [comment]
Is there a reason you're not using the stable build (1.0.0)?

**Comment by paramono** [comment]
@luke-z 
I've tried the stable build, but I am still experiencing the same issue with it.
rc11, however, works just fine
