### ISSUE TITLE
Can't create new project in 3.0.0-rc.13

### ISSUE THREAD

**Issue by jdgamble555** [nuxt/framework#8934]
### Environment

I get this error

```
No response returned from render handler: /__nuxt_error?url=/&statusCode=500&statusMessage=Vite+Error&message=
[vite-node]+[ERR_INVALID_URL_SCHEME]+/node_modules/ufo/dist/index.mjs&stack=%3Cpre%3E%3Cspan+class=
%22stack+internal%22%3Eat+/node_modules/ufo/dist/index.mjs%3C/span%3E%3C/pre%3E&data
```

### Reproduction

Using node v18.12.1 on Windows 11.  Create a new project and try to run it.

Downgrading to `3.0.0-rc-12` seems to fix the problem, although there is the [head.addEntry](https://github.com/nuxt/framework/issues/8929) problem instead.

### Describe the bug

Can't run any new projects.

**Comment by murugappanrm** [comment]
I have the same problem. I think the RC13 is broken!

**Comment by harlan-zw** [comment]
Possibly try again given the other issue is fixed https://github.com/nuxt/framework/issues/8929

You may need to clear node_modules / lock files, etc

**Comment by murugappanrm** [comment]
I tried again about 2 hours ago and now its working.

**Comment by jdgamble555** [comment]
This is still an issue! Why was this close!? This is a completely different issue than [#8929](https://github.com/nuxt/framework/issues/8929). Please re-open and do not close until there is an actual change in the core code.

Thanks,

J

**Comment by manniL** [comment]
@jdgamble555 Please check if you have special characters in your folder path, like spaces or umlauts etc.

**Comment by jdgamble555** [comment]
There are no special characters.  This happens with any new project, so I cannot use Nuxt at all. 

J

**Comment by jdgamble555** [comment]
Ok, wait, yes my root folder has a space in it, but that is where all my projects are stored.  Is there not a fix for this?

J

**Comment by manniL** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/640208/201528493-2fc037b1-46d7-4535-ac4d-df18ef5b28a4.png">

Cannot reproduct, though I'm not on a windows machine.

As I mentioned, please ensure there are no special characters (é, ä, spaces, ...) at all in your whole path, not only the project folder itself.

**Comment by manniL** [comment]
> Ok, wait, yes my root folder has a space in it, but that is where all my projects are stored. Is there not a fix for this?
> 
> J

You can try out the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), ideally there is a fix there already.

**Comment by jdgamble555** [comment]
Same error.  It looks like `npm:nuxt3@latest` still installs `3.0.0-rc.13 `.

J

**Comment by manniL** [comment]
Alright. Leaving this open hear then after #8706 got closed ☺️

**Comment by manniL** [comment]
Consolidating in https://github.com/nuxt/framework/issues/9074

**Comment by akaminator** [comment]
I reproduced it on a folder path that contains Japanese character (a kind of double-byte character) too.

**Comment by jewpaltz** [comment]
Bug still exists in release version 3.0.0
Workaround - make sure there are no spaces in the path

**Comment by manniL** [comment]
Yes, that's why I wrote to consolidate in #9074 😊

**Comment by m0zz094** [comment]
Still a problem (I obviously can't simply rename my windows user folder and break everything else just to fix this bug)

**Comment by murugappanrm** [comment]
I never create anything with the folder or file name containing spaces. Always used kebab case. Saves lots of headache as i had many issues with Centos and Linux when deployment.

**Comment by manniL** [comment]
> Still a problem (I obviously can't simply rename my windows user folder and break everything else just to fix this bug)

Can you kindly read the comment straight above you and follow the issue there? Thanks 😋
