### ISSUE TITLE
[3.0.0-rc.14] Runtime uncaught error on wrong export of `useActiveRoute` 

### ISSUE THREAD

**Issue by qnp** [nuxt/framework#9053]
### Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.14`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `telemetry`, `typescript`, `vite`, `css`, `serverHandlers`, `build`, `nitro`, `sourcemap`, `modules`, `sentry`, `components`, `runtimeConfig`
- Runtime Modules:  `./modules/nuxt/i18n`, `./modules/nuxt/sentry`, `@vueuse/nuxt@9.5.0`, `@pinia/nuxt@0.4.3`
- Build Modules:    `-`
------------------------------
```

### Reproduction

This issue does not need a repro

### Describe the bug

Using the fresh new `nuxt@3.0.0-rc.14`, we have this error in runtime:

```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/nuxt/dist/app/index.mjs?v=b6dbe5b1' does not provide an export named 'useActiveRoute' (at imports.mjs:3:279)
```

Which does not alter the behavior of the app, but maybe it should be clean before the stable release

**Comment by danielroe** [comment]
This is resolved in the latest edge release.

**Comment by qnp** [comment]
@danielroe thanks for your feedback. When speaking of "edge release" do you mean the stable 3.0.0 ? 
FYI I'm still seeing this error on this new version (congrats btw for the final release)
