### ISSUE TITLE
Typo/Bug in doc

### ISSUE THREAD

**Issue by chalist** [nuxt/framework#9054]
### Environment

Nuxi 3.0.0-rc.13                                                                                                                                                                                             15:58:17
RootDir: C:/Users/User/www/nuxt-framework                                                                                                                                                                 15:58:18
Nuxt project info:                                                                                                                                                                                           15:58:18

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.9.0`
- Nuxt Version:     `workspace:*`
- Nitro Version:    `-`
- Package Manager:  `pnpm@7.15.0`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/nuxt/framework

### Describe the bug

I see these lines in [the doc](https://nuxt.com/docs/guide/directory-structure/plugins):

![image](https://user-images.githubusercontent.com/1072154/202181250-f8e5b5a3-cd92-4d89-9990-8b8a90de93f4.png)

I clone Nuxt repo for creating MR. But I see these lines in `main` branch:

```ts
export default defineNuxtPlugin(() => {
  return {
    provide: {
      hello: (msg: string) => `Hello ${msg}!`
    }
  }
})
```

**Comment by IsraelOrtuno** [comment]
This is fixed, seems like not deployed yet.

**Comment by vedmant** [comment]
This is still an issue: 
![Monosnap plugins: · Nuxt Directory Structure 2022-12-14 16-39-13](https://user-images.githubusercontent.com/5052406/207720427-438d6bbb-e3c0-4eed-a168-8a702e0e0ba5.jpg)
